services:
  backend-calc:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: ${NEXUS_PUSH_IMAGE:-nexus.maas.int.kronshtadt.ru:8443/maas-hosted/maas-prod-stl:latest}
    container_name: backend-calc
    environment:
      - CORS_ORIGINS=["*"]
      - CORS_ALLOW_CREDENTIALS=true
      - CORS_ALLOW_METHODS=["*"]
      - CORS_ALLOW_HEADERS=["*"]
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - maas-internal

networks:
  maas-internal:
    external: true

volumes:
  uploads:
  logs: