

"""
this file is auto generated by maas-materials-price service
"""

from typing import Dict, Any

MATERIALS: Dict[str, Dict[str, Any]] = {
    "other": {
        "label": "Другой",
        "family": "other",
        "electroplating_family": None,
        "applicable_processes": [ "other" ],
        "forms": {
            "sheet": {
                "applicable_processes": [ "other" ]
            }
        },
        "material_name": "other",
        "material_name_main": "other",
        "material_group": "other"
    },
    "plastic_PA11": {
        "label": "Пластик PA11",
        "family": "plastic_3d",
        "electroplating_family": "plastic_3d",
        "density": 1020.0,
        "applicable_processes": [ "printing" ],
        "material_name": "PA11",
        "material_name_main": "plastic",
        "minimum_order_quantity": 10.0,
        "forms": {
            "powder": {
                "price": 9250.00,
                "price_units": [ "kg" ],
                "applicable_processes": [ "printing" ]
            }
        }
    },
    "plastic_PA12": {
        "label": "Пластик PA12",
        "family": "plastic_3d",
        "electroplating_family": "plastic_3d",
        "density": 930.0,
        "applicable_processes": [ "printing" ],
        "material_name": "PA12",
        "material_name_main": "plastic",
        "minimum_order_quantity": 10.0,
        "forms": {
            "powder": {
                "price": 6500.00,
                "price_units": [ "kg" ],
                "applicable_processes": [ "printing" ]
            }
        }
    },
    "steel_Ст30": {
        "label": "Сталь Ст30",
        "family": "carbon_steel",
        "electroplating_family": "carbon_steel",
        "density": 7850.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "Ст30",
        "material_name_main": "steel",
        "material_group": "конструкционная",
        "material_name_group": "качественная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "rod": {
                "price": 950.0,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "sheet": {
                "price": 225.0,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_Ст35": {
        "label": "Сталь Ст35",
        "family": "carbon_steel",
        "electroplating_family": "carbon_steel",
        "density": 7850.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "Ст35",
        "material_name_main": "steel",
        "material_group": "конструкционная",
        "material_name_group": "качественная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "rod": {
                "price": 344.24,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "hexagon": {
                "price": 184.28,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_12Х18Н10Т": {
        "label": "Сталь 12Х18Н10Т",
        "family": "stainless_steel",
        "electroplating_family": "stainless_steel",
        "density": 7920.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "12Х18Н10Т",
        "material_name_main": "steel",
        "material_group": "конструкционная",
        "material_name_group": "коррозионно-стойкая жаропрочная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "rod": {
                "price": 1178.8,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "sheet": {
                "price": 1074.43,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_14Х17Н2": {
        "label": "Сталь 14Х17Н2",
        "family": "stainless_steel",
        "electroplating_family": "stainless_steel",
        "density": 7750.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "14Х17Н2",
        "material_name_main": "steel",
        "material_name_group": "коррозионно-стойкая жаропрочная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "rod": {
                "price": 1115.32,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "sheet": {
                "price": 1131.96,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "hexagon": {
                "price": 1997.81,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_13Х15Н4АМ3": {
        "label": "Сталь 13Х15Н4АМ3",
        "family": "stainless_steel",
        "electroplating_family": "stainless_steel",
        "density": 7850.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "13Х15Н4АМ3",
        "material_name_main": "steel",
        "material_name_group": "коррозионно-стойкая жаропрочная высокопрочная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "rod": {
                "price": 1427.89,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_Ст45": {
        "label": "Сталь Ст45",
        "family": "carbon_steel",
        "electroplating_family": "carbon_steel",
        "density": 7826.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "Ст45",
        "material_name_main": "steel",
        "material_group": "конструкционная",
        "material_name_group": "качественная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "rod": {
                "price": 154.3,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "sheet": {
                "price": 160.0,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "hexagon": {
                "price": 147.02,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_Ст10": {
        "label": "Сталь Ст10",
        "family": "carbon_steel",
        "electroplating_family": "carbon_steel",
        "density": 7856.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "Ст10",
        "material_name_main": "steel",
        "material_group": "конструкционная",
        "material_name_group": "качественная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "rod": {
                "price": 252.33,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "sheet": {
                "price": 240.34,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_Ст20": {
        "label": "Сталь Ст20",
        "family": "carbon_steel",
        "electroplating_family": "carbon_steel",
        "density": 7850.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "Ст20",
        "material_name_main": "steel",
        "material_group": "конструкционная",
        "material_name_group": "качественная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "rod": {
                "price": 153.19,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "sheet": {
                "price": 122.11,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "hexagon": {
                "price": 107.84,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_40Х13": {
        "label": "Сталь 40Х13",
        "family": "carbon_steel",
        "electroplating_family": "carbon_steel",
        "density": 7680.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "40Х13",
        "material_name_main": "steel",
        "material_name_group": "коррозионно-стойкая жаропрочная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "rod": {
                "price": 286.92,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_30ХГСА": {
        "label": "Сталь 30ХГСА",
        "family": "stainless_steel",
        "electroplating_family": "stainless_steel",
        "density": 7850.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "30ХГСА",
        "material_name_main": "steel",
        "material_group": "конструкционная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "rod": {
                "price": 349.07,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "sheet": {
                "price": 359.22,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "hexagon": {
                "price": 452.98,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_40Х": {
        "label": "Сталь 40Х",
        "family": "stainless_steel",
        "electroplating_family": "stainless_steel",
        "density": 7820.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "40Х",
        "material_name_main": "steel",
        "material_group": "конструкционная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "rod": {
                "price": 171.12,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_07Х16Н6": {
        "label": "Сталь 07Х16Н6",
        "family": "stainless_steel",
        "electroplating_family": "stainless_steel",
        "density": 7900.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "07Х16Н6",
        "material_name_main": "steel",
        "material_name_group": "коррозионно-стойкая высокопрочная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "rod": {
                "price": 1776.86,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "composite_21701": {
        "label": "Композит 21701",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "21701",
        "material_name_main": "composite",
        "material_group": "углеродная ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "textile": {
                "price": 2848.25,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.14
            },
            "pre-preg": {
                "price": 9316.73,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.14
            }
        }
    },
    "non_ferrous_АМг2": {
        "label": "Цветные металлы АМг2",
        "family": "aluminum",
        "electroplating_family": "aluminum",
        "density": 2690.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "АМг2",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 550.75,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "rod": {
                "price": 1453.59,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "non_ferrous_АМг3": {
        "label": "Цветные металлы АМг3",
        "family": "aluminum",
        "electroplating_family": "aluminum",
        "density": 2690.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "АМг3",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 407.3,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "rod": {
                "price": 725.73,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "plate": {
                "price": 685.7,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "non_ferrous_АМг6": {
        "label": "Цветные металлы АМг6",
        "family": "aluminum",
        "electroplating_family": "aluminum",
        "density": 2650.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "АМг6",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 779.76,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "plate": {
                "price": 639.18,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "rod": {
                "price": 850.21,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_Ст3": {
        "label": "Сталь Ст3",
        "family": "carbon_steel",
        "electroplating_family": "carbon_steel",
        "density": 7850.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "Ст3",
        "material_name_main": "steel",
        "material_group": "конструкционная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 127.26,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "rod": {
                "price": 91.01,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_65Г": {
        "label": "Сталь 65Г",
        "family": "stainless_steel",
        "electroplating_family": "stainless_steel",
        "density": 7850.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "65Г",
        "material_name_main": "steel",
        "material_group": "конструкционная",
        "material_name_group": "качественная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 138.15,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "non_ferrous_Д16": {
        "label": "Цветные металлы Д16",
        "family": "aluminum",
        "electroplating_family": "aluminum",
        "density": 2800.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "Д16",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 1038.57,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "plate": {
                "price": 580.3,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "rod": {
                "price": 793.43,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "non_ferrous_Д16Т": {
        "label": "Цветные металлы Д16Т",
        "family": "aluminum",
        "electroplating_family": "aluminum",
        "density": 2800.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "Д16Т",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 750.22,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "plate": {
                "price": 583.16,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "rod": {
                "price": 698.87,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "non_ferrous_М1": {
        "label": "Цветные металлы М1",
        "family": "copper",
        "electroplating_family": "copper",
        "density": 8940.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "М1",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "material_name_group": "высокочистый",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 1638.39,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "rod": {
                "price": 1171.5,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "non_ferrous_Л63": {
        "label": "Цветные металлы Л63",
        "family": "latun",
        "electroplating_family": "latun",
        "density": 8440.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "Л63",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 3532.58,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "rod": {
                "price": 1300.55,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "non_ferrous_М3": {
        "label": "Цветные металлы М3",
        "family": "copper",
        "electroplating_family": "copper",
        "density": 8940.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "М3",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 1106.99,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "non_ferrous_ОТ4": {
        "label": "Цветные металлы ОТ4",
        "family": "titanium",
        "electroplating_family": "titanium",
        "density": 4550.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "ОТ4",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "material_name_group": "коррозионно-стойкая жаропрочная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 4171.63,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "plate": {
                "price": 3462.96,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "rod": {
                "price": 3130.64,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "plastic_PETG": {
        "label": "Пластик PETG",
        "family": "plastic_3d",
        "electroplating_family": "plastic_3d",
        "density": 1300.0,
        "applicable_processes": [ "printing" ],
        "material_name": "PETG",
        "material_name_main": "plastic",
        "minimum_order_quantity": 10.0,
        "forms": {
            "thread": {
                "price": 1030.73,
                "price_units": [ "kg" ],
                "applicable_processes": [ "printing" ]
            }
        }
    },
    "plastic_ABS": {
        "label": "Пластик ABS",
        "family": "plastic_3d",
        "electroplating_family": "plastic_3d",
        "density": 1080.0,
        "applicable_processes": [ "printing" ],
        "material_name": "ABS",
        "material_name_main": "plastic",
        "minimum_order_quantity": 10.0,
        "forms": {
            "thread": {
                "price": 2010.33,
                "price_units": [ "kg" ],
                "applicable_processes": [ "printing" ]
            }
        }
    },
    "non_ferrous_АК4": {
        "label": "Цветные металлы АК4",
        "family": "aluminum",
        "electroplating_family": "aluminum",
        "density": 2790.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "АК4",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "material_name_group": "жаропрочная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "plate": {
                "price": 937.43,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "rod": {
                "price": 783.85,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "non_ferrous_ВТ6": {
        "label": "Цветные металлы ВТ6",
        "family": "titanium",
        "electroplating_family": "titanium",
        "density": 4450.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "ВТ6",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "material_name_group": "высокопрочная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "plate": {
                "price": 3361.7,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "rod": {
                "price": 7340.59,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "sheet": {
                "price": 4867.93,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "composite_Т10": {
        "label": "Композит Т10",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "Т10",
        "material_name_main": "composite",
        "material_group": "стеклянная ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "pre-preg": {
                "price": 2940.0,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.23
            },
            "textile": {
                "price": 371.85,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.23
            }
        }
    },
    "composite_10270": {
        "label": "Композит 10270",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "10270",
        "material_name_main": "composite",
        "material_group": "углеродная ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "pre-preg": {
                "price": 16080.0,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.2
            }
        }
    },
    "composite_10524": {
        "label": "Композит 10524",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "10524",
        "material_name_main": "composite",
        "material_group": "углеродная ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "pre-preg": {
                "price": 14428.0,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.2
            }
        }
    },
    "composite_22502": {
        "label": "Композит 22502",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "22502",
        "material_name_main": "composite",
        "material_group": "углеродная ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "pre-preg": {
                "price": 8736.0,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.208
            },
            "textile": {
                "price": 3862.16,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.208
            }
        }
    },
    "composite_Т25": {
        "label": "Композит Т25",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "Т25",
        "material_name_main": "composite",
        "material_group": "стеклянная ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "pre-preg": {
                "price": 5144.0,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.3
            }
        }
    },
    "composite_Т15": {
        "label": "Композит Т15",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "Т15",
        "material_name_main": "composite",
        "material_group": "стеклянная ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "pre-preg": {
                "price": 3240.0,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.2
            },
            "textile": {
                "price": 325.0,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.2
            }
        }
    },
    "composite_Т64": {
        "label": "Композит Т64",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "Т64",
        "material_name_main": "composite",
        "material_group": "стеклянная ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "pre-preg": {
                "price": 4145.0,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.25
            },
            "textile": {
                "price": 1070.0,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.25
            }
        }
    },
    "non_ferrous_БрАЖМц10-3-1.5": {
        "label": "Цветные металлы БрАЖМц10-3-1.5",
        "family": "bronze",
        "electroplating_family": "bronze",
        "density": 7800.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "БрАЖМц10-3-1.5",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "minimum_order_quantity": 10.0,
        "forms": {
            "rod": {
                "price": 1531.42,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "composite_ТС-8/3-К": {
        "label": "Композит ТС-8/3-К",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "ТС-8/3-К",
        "material_name_main": "composite",
        "material_group": "кварцевая ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "textile": {
                "price": 10485.93,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.28
            },
            "pre-preg": {
                "price": 17022.0,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.28
            }
        }
    },
    "composite_КТ11": {
        "label": "Композит КТ11",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "КТ11",
        "material_name_main": "composite",
        "material_group": "кремнеземная ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "textile": {
                "price": 1410.0,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.4
            }
        }
    },
    "composite_ТР-560": {
        "label": "Композит ТР-560",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "ТР-560",
        "material_name_main": "composite",
        "material_group": "ровинговая ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "textile": {
                "price": 90.17,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.45
            }
        }
    },
    "composite_Т23": {
        "label": "Композит Т23",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "Т23",
        "material_name_main": "composite",
        "material_group": "стеклянная ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "textile": {
                "price": 166.67,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.27
            }
        }
    },
    "composite_Э3-180": {
        "label": "Композит Э3-180",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "Э3-180",
        "material_name_main": "composite",
        "material_group": "стеклянная ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "textile": {
                "price": 125.0,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.18
            }
        }
    },
    "composite_24252": {
        "label": "Композит 24252",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "24252",
        "material_name_main": "composite",
        "material_group": "углеродная ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "textile": {
                "price": 2440.0,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.28
            }
        }
    },
    "steel_12Х2НВФА": {
        "label": "Сталь 12Х2НВФА",
        "family": "stainless_steel",
        "electroplating_family": "stainless_steel",
        "density": 7850.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "12Х2НВФА",
        "material_name_main": "steel",
        "material_group": "конструкционная",
        "material_name_group": "высококачественная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "rod": {
                "price": 384.6,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "sheet": {
                "price": 1111.95,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_15Х18Н12С4ТЮ": {
        "label": "Сталь 15Х18Н12С4ТЮ",
        "family": "stainless_steel",
        "electroplating_family": "stainless_steel",
        "density": 7850.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "15Х18Н12С4ТЮ",
        "material_name_main": "steel",
        "material_name_group": "коррозионно-стойкая",
        "minimum_order_quantity": 10.0,
        "forms": {
            "rod": {
                "price": 1228.4,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "sheet": {
                "price": 2562.03,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_08Х15Н5Д2Т": {
        "label": "Сталь 08Х15Н5Д2Т",
        "family": "stainless_steel",
        "electroplating_family": "stainless_steel",
        "density": 7780.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "08Х15Н5Д2Т",
        "material_name_main": "steel",
        "material_name_group": "коррозионно-стойкая жаропрочная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 1734.56,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_Ст1": {
        "label": "Сталь Ст1",
        "family": "carbon_steel",
        "electroplating_family": "carbon_steel",
        "density": 7850.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "Ст1",
        "material_name_main": "steel",
        "material_group": "конструкционная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 155.72,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "steel_Ст25": {
        "label": "Сталь Ст25",
        "family": "carbon_steel",
        "electroplating_family": "carbon_steel",
        "density": 7850.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "Ст25",
        "material_name_main": "steel",
        "material_group": "конструкционная",
        "material_name_group": "качественная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 205.5,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "rod": {
                "price": 285.55,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "non_ferrous_АД1": {
        "label": "Цветные металлы АД1",
        "family": "aluminum",
        "electroplating_family": "aluminum",
        "density": 2700.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "АД1",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "material_name_group": "высокочистый",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 545.62,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "rod": {
                "price": 438.66,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "non_ferrous_АМц": {
        "label": "Цветные металлы АМц",
        "family": "aluminum",
        "electroplating_family": "aluminum",
        "density": 2780.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "АМц",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 451.16,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "rod": {
                "price": 548.88,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "non_ferrous_ВТ1-0": {
        "label": "Цветные металлы ВТ1-0",
        "family": "titanium",
        "electroplating_family": "titanium",
        "density": 4520.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "ВТ1-0",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "material_name_group": "высокочистый",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 2091.41,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "non_ferrous_ВТ5-1": {
        "label": "Цветные металлы ВТ5-1",
        "family": "titanium",
        "electroplating_family": "titanium",
        "density": 4425.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "ВТ5-1",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "material_name_group": "жаропрочная",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 4165.17,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            },
            "rod": {
                "price": 3385.86,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "non_ferrous_Д1АМ": {
        "label": "Цветные металлы Д1АМ",
        "family": "aluminum",
        "electroplating_family": "aluminum",
        "density": 2800.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "Д1АМ",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 960.49,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "non_ferrous_М2": {
        "label": "Цветные металлы М2",
        "family": "copper",
        "electroplating_family": "copper",
        "density": 8940.0,
        "applicable_processes": [ "cnc-milling", "electroplating_auto" ],
        "material_name": "М2",
        "material_name_main": "non_ferrous",
        "material_group": "деформируемый сплав",
        "minimum_order_quantity": 10.0,
        "forms": {
            "sheet": {
                "price": 1119.67,
                "price_units": [ "kg" ],
                "applicable_processes": [ "cnc-milling", "electroplating_auto" ]
            }
        }
    },
    "composite_МКТ-5.25": {
        "label": "Композит МКТ-5.25",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "МКТ-5.25",
        "material_name_main": "composite",
        "material_group": "кремнеземная ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "textile": {
                "price": 31450.0,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 7.2
            }
        }
    },
    "composite_Т11": {
        "label": "Композит Т11",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "Т11",
        "material_name_main": "composite",
        "material_group": "стеклянная ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "textile": {
                "price": 154.16,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.25
            }
        }
    },
    "composite_Т13": {
        "label": "Композит Т13",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "Т13",
        "material_name_main": "composite",
        "material_group": "стеклянная ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "textile": {
                "price": 126.26,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.27
            }
        }
    },
    "composite_Э1": {
        "label": "Композит Э1",
        "family": "polymer_composites",
        "electroplating_family": "polymer_composites",
        "applicable_processes": [ "composite" ],
        "material_name": "Э1",
        "material_name_main": "composite",
        "material_group": "стеклянная ткань",
        "minimum_order_quantity": 10.0,
        "forms": {
            "textile": {
                "price": 195.0,
                "price_units": [ "m", "m2" ],
                "applicable_processes": [ "composite" ],
                "one_layer_thickness": 0.2
            }
        }
    }
}
